### ISSUE TITLE
delete room data

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/xo-game#19]
გათვალისწინებული გაქვთ როგორ უნდა დარესეტდეს თამაში, თუ მოთამაშეები გაიყარნენ?

**Comment by toka16** [comment]
რას ქვია გაიყარნენ?? თუკი თამაში ჯერ არ დამთავრებულა და ისე შეუწყდათ ვთქვათ ინტერნეტთან კავშირი მაშინ როცა აღადგენენ მაშინ გააგრძელებენ,  დროის შეზღუდვა არ გვაქვს

**Comment by toka16** [comment]
ერთი ისაა გასარკვევი როცა დამთავრდება თამაში მაშინვე რო წავშალოთ ამ თამაშის ინფორმაცია გააფუჭებს თუ არა საქმეს?? მე მგონია რო ჯობია რაღაც დროის მერე, მაგალითად 1 წუთის მერე წავშალოთ

**Comment by gkiko** [comment]
დამთავრებისთანავე წაშლა აჯობებს მგონი, რადგან ერთ ხელს რომ მორჩებიან,
მაშინვე მეორეს დავაწყებინებ ოთახიდან გამოსვლის გარეშე. ძველი ინფორმაცია თუ
შეინახება, 1 წუთი მოცდა მოგვიწევს სანამ ახალ ხელს დავიწყებთ.

თამაშის ინფორმაციის წაშლაზე ნაადრევად მომივიდა issue-ს გახსნა. კიდე
გამოვიკვლევ რაღაცეებს და მოგწერ

**Comment by gkiko** [comment]
ვგეგმავ, რომ ზედიზედ რამდენიმე ხელი ვათამაშო ოთახიდან გასვლის გარეშე. ამისთვის საჭიროა, რომ პირველი ხელის დამთავრების შემდეგ ოთახზე მიბმული დაფის ინფორმაცია გაასუფთაოთ. თითქოს ახლადშემოერთებული მოთამაშეები იწყენებ თამაშს

**Comment by toka16** [comment]
კარგი, როცა თამაში დამთავრდება, მოთამაშეს, რომელმაც ბოლოს გააკეთა სვლა, მაშინვე უბრუნდება დასრულებული თამაშის ინფორმაცია, ხოლო როცა მეორე მოთამაშეც გააკეთებს get request-ს ამ თამაშზე, მას დაუბრუნდება თამაშის ინფორმაცია და თან ეს თამაში წაიშლება მეხსიერებიდან. პრობლემა შეძლება იყოს, თუკი მეორე მოთამაშემდე სხვა გააკეთებს GET request-ს, მაშინ მეორე მოთამაშე თამაშის დასრულებას ვეღარ გაიგებს. თუ ეგ რამე პრობლემას გიქმნის დაწერე და მაგასაც გამოვასწორებთ

**Comment by toka16** [comment]
დავამატე ოთახის წაშლა თამაშის დამთავრების შემდეგ
github: https://github.com/freeuni-sdp/xo-game/commit/5e8bb42ee7f2ea652f5637c0a2f8717f75da46c1

**Comment by gkiko** [comment]
თამაში რომ მორჩება, თავიდან გამოვგზავნით შემოერთწბის მოთხოვნას. ორივესგან
რომ მიიღებ, მერე წაშალე ძველი და ახალი მდგომარეობა დააბრუნე.

**Comment by toka16** [comment]
კარგი, ეგრე ვქენი, თამაშის ძველი მდგომარეობა წაიშლება მაშინ, როცა ორივე მოთამაშე ახლიდან დარეგისტრირდება თამაშზე.
P.S. აუცილებელი არ არის რომ იგივე მოთამაშეები დარეგისტრირდნენ, მაგ შეზღუდვის შემთხვევაში სხვა პრობლემები წარმოიქმნებოდა..

**Comment by toka16** [comment]
ესეც commit-ის ლინკი:
https://github.com/freeuni-sdp/xo-game/commit/292b1c5e2251b3c6f46dbfa9b8adb77a903c2174
