### ISSUE TITLE
board state not reset

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/xo-game#21]
დროის გასვლის შემდეგ დაუსრულებელი თამაში მდგომარეობა არ იშლება.

ოთახში შესვლის შემდეგ მხვდება ადრე ნათამაშები დაფა.

**Comment by toka16** [comment]
გავასწორე ეს ბაგი, თუკი თამაშს 5 წუთის განმავლობაში არავინ არ მიაკითხავს (დარეგისტრირდება თამაშზე, მოითხოვს თამაშის მდგომარეობას ან გააკეთებს სვლას) მაშინ ეს თამაში გაუქმდება, წაიშლება მეხსიერებიდან. მოთამაშეების ქულებზე ეს გავლენას არ იქონიებს.

**Comment by toka16** [comment]
ესეც commit-ის ლინკი: https://github.com/freeuni-sdp/xo-game/commit/9af74358092746eec6e0934298884bd6f67547fc

**Comment by gkiko** [comment]
:clap:
